### ISSUE TITLE
Escaping multiple characters result in IndexOutOfBoundsException

### ISSUE THREAD

**Issue by paulfvliz** [owlike/genson#147]
I've noticed that when serializing a map that has key with a few characters that require escaping that an IndexOutOfBoundsException is thrown. Consider the following code snippet

```java  @Test
  public void testMultipleEscapeChars() {
	  Genson genson = new GensonBuilder().create();    
	  Map<String,Double> m = new HashMap<>();
          m.put("a\nb\nc", 1.0d);
          assertThat(genson.serialize(m), equalTo("{\"a\\nb\\nc\":1.0}"));
  }
```

Results in 
```
com.owlike.genson.JsonBindingException: Failed to serialize object of type class java.util.HashMap

	at com.owlike.genson.Genson.serialize(Genson.java:277)
	at com.owlike.genson.Genson.serialize(Genson.java:170)
	at org.my.genson.GensonTest.testMultipleEscapeChars(GensonTest.java:113)
        ...
Caused by: java.lang.IndexOutOfBoundsException: start 2, end 1, s.length() 5
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
	at java.lang.StringBuilder.append(StringBuilder.java:175)
	at com.owlike.genson.stream.JsonWriter.escapeString(JsonWriter.java:431)
	at com.owlike.genson.stream.JsonWriter.writeName(JsonWriter.java:230)
	at com.owlike.genson.stream.JsonWriter.writeName(JsonWriter.java:10)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.serialize(DefaultConverters.java:644)
	at com.owlike.genson.convert.DefaultConverters$MapConverter.serialize(DefaultConverters.java:620)
	at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.serialize(NullConverterFactory.java:69)
	at com.owlike.genson.Genson.serialize(Genson.java:274)
	... 28 more
```

This might be related to issue #112

**Comment by EugenCepoi** [comment]
Thanks for reporting this, indeed this is a bug. Fixed in here https://github.com/owlike/genson/pull/148.
The PR you referenced was indeed proposing a fix for it which I overlooked and thought wrong.
