### ISSUE TITLE
Serialization fails due to @JsonProperty annotation

### ISSUE THREAD

**Issue by tibetiroka** [owlike/genson#169]
In certain cases, having fields annotated with JsonProperty to specify aliases can cause the _serialization_ of the object to fail with ConcurrentModificationException.

Example:

We have a dummy class for testing:
```
public class TestClass{
	protected boolean first;
	protected boolean second;
}
```
Serialization works as expected. Now, let's add some annotations:
```
public class TestClass{
	@JsonProperty(aliases = {"first"})
	protected boolean first;
	@JsonProperty(aliases = {"second"})
	protected boolean second;
}
```
It still works just alright. The bug comes out when we add an other alias to the fields:
```
public class TestClass{
	@JsonProperty(aliases = {"first","first_"})
	protected boolean first;
	@JsonProperty(aliases = {"second"})
}
```
And we get:
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1579)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1607)
	at com.owlike.genson.reflect.AbstractBeanDescriptorProvider.provide(AbstractBeanDescriptorProvider.java:134)
	at com.owlike.genson.reflect.BeanDescriptorProvider$CompositeBeanDescriptorProvider.provide(BeanDescriptorProvider.java:60)
	at com.owlike.genson.convert.BasicConvertersFactory.provide(BasicConvertersFactory.java:104)
	at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:69)
	at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:51)
	at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:75)
	at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:64)
	at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:66)
	at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:20)
	at com.owlike.genson.Genson.provideConverter(Genson.java:148)
	at com.owlike.genson.Genson.serialize(Genson.java:272)
	at com.owlike.genson.Genson.serialize(Genson.java:170)
```
But it doesn't stop there; the issue comes out only if we add the second alias to the first field. This works:
```
public class TestClass{
	@JsonProperty(aliases = {"first"})
	protected boolean first;
	@JsonProperty(aliases = {"second","second_"})
	protected boolean second;
}
```
It seems like the annotation works correctly on the second field, with no upper limit on the number of aliases.

Some further testing revealed that the third, fourth and presumably all other fields are also broken, supporting only a single alias.

It doesn't matter what the aliases are, or whether the value() property is set. The error seems to be consistent in each test.

**Comment by EugenCepoi** [comment]
Hi @tibetiroka , thanks for the report. That's indeed a bug, I was able to reproduce with your example. I have a fix merged in master, though I wont't release immediately because of another issue when running tests (which specific to test and shouldn't affect Genson users). Feel free to give it a shot.

**Comment by tibetiroka** [comment]
I tried it and it seems to work perfectly. Thank you for fixing this issue so quickly!
