### ISSUE TITLE
java.lang.IllegalArgumentException: wrong number of arguments while serializing LocalDateTime object.

### ISSUE THREAD

**Issue by slaaridh** [owlike/genson#174]
Hello,

I have the following stacktrace when I tried to serialize a LocalDateTime object. It seems that genson consider the "LocalDateTime .isAfter" method as an accessor,  however this is not the case.

java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.owlike.genson.reflect.PropertyAccessor$MethodAccessor.access(PropertyAccessor.java:64)
	at com.owlike.genson.reflect.PropertyAccessor.serialize(PropertyAccessor.java:24)
	at com.owlike.genson.reflect.BeanDescriptor.serialize(BeanDescriptor.java:92)
	at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.serialize(NullConverterFactory.java:69)
	at com.owlike.genson.reflect.PropertyAccessor.serialize(PropertyAccessor.java:27)
	at com.owlike.genson.reflect.BeanDescriptor.serialize(BeanDescriptor.java:92)
	at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.serialize(NullConverterFactory.java:69)
	at com.owlike.genson.Genson.serialize(Genson.java:274)
	at com.owlike.genson.ext.jaxrs.GensonJsonConverter.writeTo(GensonJsonConverter.java:85)

Kind regards

**Comment by EugenCepoi** [comment]
Hi  @slaaridh , by default Genson doesn't know how to treat these types so it's considering them the same as classic java beans. For java.time types to be correctly supported you can take a look at this https://github.com/owlike/genson/tree/master/genson-java-datetime.
