### ISSUE TITLE
RuntimeType seralizing should not use type looser than static type

### ISSUE THREAD

**Issue by kerler** [owlike/genson#97]
For below source code:

`
    public class TestPerson {
        private SortedMap<String, Object> sortedMapStrObj;
        ......
    }

    SortedMap<String, Object> mapStrArea = new TreeMap<String, Object>();
    mapStrArea.put("beijingAreaKey2", new Area("beijingAreaObj2"));
    mapStrArea.put("shanghaiAreaKey2", new Area("shanhaiAreaObj2"));
    testPerson.setSortedMapStrObj(mapStrArea);

    new GensonBuilderRevised()
                .useIndentation(true)
                .useRuntimeType(true)
                .useClassMetadata(true)
                .useFields(true, VisibilityFilter.PRIVATE)
                .create()
                .serialize(testPerson)
`

In call stack trace, the line 272 in Genson.serialize() calls MapConverterFactory.create() and it can judge that the type of key of field `TestPerson.sortedMapStrObj` is String. The line 274 also calls MapConverterFactory.create() but it use 'Object' as the type of the key. The runtime type--here 'Object'--should not be looser than static type--here 'String'. Genson need to judge that the runtime type is or is sub class of the static type. 

The call traces for line 272 and line 274 are in attached files. The serialize()/deserialize() works well just because MapConverterFactory.create() does not distinguish Object against String too much. But if I want to overwrite MapConverterFactory to support complex key of map, it will have problem.

`
public final class Genson {
public void serialize(Object object, Type type, ObjectWriter writer, Context ctx) {
    Serializer<Object> ser = provideConverter(type); //line 272
    try {
      ser.serialize(object, writer, ctx); //line 274
      writer.flush();
    } catch (Exception e) {
      throw new JsonBindingException("Failed to serialize object of type " + type, e);
    }
  }
`

**Comment by kerler** [comment]
Line 272 call trace:

"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at MapConverterFactory.create()
	  at com.owlike.genson.convert.BasicConvertersFactory.provide(BasicConvertersFactory.java:97)
	  at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:69)
	  at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:51)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:75)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:64)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:55)
	  at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:19)
	  at com.owlike.genson.Genson.provideConverter(Genson.java:148)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider.provide(AbstractBeanDescriptorProvider.java:166)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider.provide(AbstractBeanDescriptorProvider.java:119)
	  at com.owlike.genson.reflect.BeanDescriptorProvider$CompositeBeanDescriptorProvider.provide(BeanDescriptorProvider.java:60)
	  at com.owlike.genson.convert.BasicConvertersFactory.provide(BasicConvertersFactory.java:104)
	  at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:69)
	  at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:51)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:75)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:64)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:55)
	  at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:19)
	  at com.owlike.genson.Genson.provideConverter(Genson.java:148)
	  at com.owlike.genson.Genson.serialize(Genson.java:272)
	  at com.owlike.genson.Genson.serialize(Genson.java:170)

**Comment by kerler** [comment]
Line 272 call trace:
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at MapConverterFactory.create()
	  at com.owlike.genson.convert.BasicConvertersFactory.provide(BasicConvertersFactory.java:97)
	  at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:69)
	  at com.owlike.genson.convert.BasicConvertersFactory.create(BasicConvertersFactory.java:51)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:75)
	  at com.owlike.genson.reflect.AbstractBeanDescriptorProvider$ContextualFactoryDecorator.create(AbstractBeanDescriptorProvider.java:64)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:88)
	  at com.owlike.genson.convert.ChainedFactory.create(ChainedFactory.java:75)
	  at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:55)
	  at com.owlike.genson.convert.CircularClassReferenceConverterFactory.create(CircularClassReferenceConverterFactory.java:19)
	  at com.owlike.genson.Genson.provideConverter(Genson.java:148)
	  at com.owlike.genson.Genson.serialize(Genson.java:272)
	  at com.owlike.genson.convert.RuntimeTypeConverter.serialize(RuntimeTypeConverter.java:41)
	  at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.serialize(NullConverterFactory.java:69)
	  at com.owlike.genson.reflect.PropertyAccessor.serialize(PropertyAccessor.java:27)
	  at com.owlike.genson.reflect.BeanDescriptor.serialize(BeanDescriptor.java:92)
	  at com.owlike.genson.convert.ClassMetadataConverter.serialize(ClassMetadataConverter.java:83)
	  at com.owlike.genson.convert.RuntimeTypeConverter.serialize(RuntimeTypeConverter.java:43)
	  at com.owlike.genson.convert.NullConverterFactory$NullConverterWrapper.serialize(NullConverterFactory.java:69)
	  at com.owlike.genson.Genson.serialize(Genson.java:274)
	  at com.owlike.genson.Genson.serialize(Genson.java:170)

**Comment by EugenCepoi** [comment]
You are right, the type will be lost in RuntimeTypeConverter. I used there the raw class on purpose as anyway, if this is a container, we will lookup the concrete types for its elements too.

I think the fix would be to pass the generic type to RuntimeTypeConverter when creating it, not only the raw class. Then in there using TypeUtil.expand(currentObject.getClass, staticType) and use this type when calling again serialize. However TypeUtil.expand doesn't expand raw classes yet... so in short this might be way more involved than what it looks like. Also doing this for every single property that needs to be serialized at runtime would be costly on the performances.

Depending on how you want to serialize your complex keys, there is already a feature in genson which will support ser/de of complex maps. However it is not using a json object layout but rather an json array of json objects, where each object is a key/value.

**Comment by kerler** [comment]
Dear Sir,

I used code in attached 'genson.zip' to fix or workaround below issues. The code is just using  Genson lib jar through inheritance and reflection, without directly modify source code of Genson. When you publish your fix in the future, I will obsolete those code in attached 'genson.zip'.

#97 RuntimeType seralizing should not use type looser than static type, 
#95 Handle SortedMap,
#96 Use metadata for java primitive type wrapper classes,
#63 Don't use toString when ser. complex keys of unknown type.

[genson.zip](https://github.com/owlike/genson/files/329026/genson.zip)


Below 'GensonBuilderRevised.java' is one of the classes in attached 'genson.zip'.

`
package org.springframework.data.gremlin.utils.json.genson;

import com.owlike.genson.*;
import com.owlike.genson.convert.DefaultConverters;
import com.owlike.genson.reflect.BeanPropertyFactory;
import com.owlike.genson.reflect.BeanViewDescriptorProvider;
import org.apache.commons.lang3.reflect.FieldUtils;

import java.lang.reflect.Field;
import java.text.DateFormat;
import java.util.List;
import java.util.Map;

/**
 * Created by liubaogang on 2016/6/15.
 */
public class GensonBuilderRevised extends GensonBuilder {

    AdditionalConfigurationForGenson additionalConfigurationForGenson = new AdditionalConfigurationForGenson();

    public GensonBuilderRevised setForcingPrimaryWrapperFieldNeedingRuntimeMetadata(boolean forcingPrimaryWrapperFieldNeedingRuntimeMetadata) {
        additionalConfigurationForGenson.setForcingPrimaryWrapperFieldNeedingRuntimeMetadata(forcingPrimaryWrapperFieldNeedingRuntimeMetadata);
        return this;
    }

    public GensonBuilderRevised addPrimaryWrapperFieldNeedingRuntimeMetadata(Class<?> concreteClassContainingField, Field field){
        additionalConfigurationForGenson.addPrimaryWrapperFieldNeedingRuntimeMetadata(concreteClassContainingField, field);
        return this;
    }

    public GensonBuilderRevised addPrimaryWrapperFieldNeedingRuntimeMetadata(Class<?> concreteClassContainingField, String fieldName){
        additionalConfigurationForGenson.addPrimaryWrapperFieldNeedingRuntimeMetadata(concreteClassContainingField, fieldName);
        return this;
    }

    @Override
    protected void addDefaultConverterFactories(List<Factory<? extends Converter<?>>> factories) {
        factories.add(DefaultConverters.ArrayConverterFactory.instance);
        factories.add(DefaultConverters.CollectionConverterFactory.instance);
        factories.add(MapConverterFactoryRevised.instance); //factories.add(DefaultConverters.MapConverterFactory.instance);
        factories.add(DefaultConverters.EnumConverterFactory.instance);
        factories.add(PrimitiveConverterFactoryRevised.instance);//factories.add(DefaultConverters.PrimitiveConverterFactory.instance);
        factories.add(DefaultConverters.UntypedConverterFactory.instance);
        try {
            factories.add(new DefaultConverters.CalendarConverterFactory(
                    //new DefaultConverters.DateConverter(dateFormat, useDateAsTimestamp)
                    new DefaultConverters.DateConverter((DateFormat)FieldUtils.readField(this, "dateFormat", true), (Boolean) FieldUtils.readField(this, "useDateAsTimestamp", true))

            ));
        } catch (IllegalAccessException e) {
            throw new IllegalStateException(e);
        }
    }

    @Override
    protected BeanPropertyFactory createBeanPropertyFactory() {
        try{
            return doGetBeanPropertyFactory();
        } catch (IllegalAccessException e) {
            throw new IllegalStateException(e);
        }
    }

    private BeanPropertyFactory doGetBeanPropertyFactory() throws IllegalAccessException {
        final List<BeanPropertyFactory> beanPropertyFactories = (List<BeanPropertyFactory>) FieldUtils.readField(this, "beanPropertyFactories", true);
        if ((Boolean) FieldUtils.readField(this, "withBeanViewConverter", true)) {
            beanPropertyFactories.add(new BeanViewDescriptorProvider.BeanViewPropertyFactory(
                    (Map<Class<?>, BeanView<?>>) FieldUtils.readField(this, "registeredViews", true)
            ));
        }
        beanPropertyFactories.add(new BeanPropertyStandardFactoryRevised()); //beanPropertyFactories.add(new BeanPropertyFactory.StandardFactory());
        return new BeanPropertyFactory.CompositeFactory(beanPropertyFactories);
    }

    @Override
    protected Genson create(Factory<Converter<?>> converterFactory, Map<String, Class<?>> classAliases) {
        setAdditionalConfigurationForGenson();
        return super.create(converterFactory, classAliases);
    }

    private void setAdditionalConfigurationForGenson() {
        /**
         * To store additional configuration for Genson, take use a map_entry in 'Genson::Map<Class<?>, Object> defaultValues'.
         * Genson.java is final class and we do not want to modify Genson lib's source code, so we have to use this tricky way.
         */
        this.useDefaultValue(additionalConfigurationForGenson, AdditionalConfigurationForGenson.class);
    }
}

`

Thanks,
Baogang

**Comment by EugenCepoi** [comment]
Thank you, I'll have a look at your improvements. You should open some pull requests with your code. It will be much nicer to review and get integrated in genson.
